name: "Multi event pipeline"
on:
    push:
        branches:
            - master
            - test


jobs:
    on-push:
        runs-on: ubuntu-latest
        steps:
            - name: "Running on master/test push"
              run: echo "Running on master/test push"